spring.application.name=CardHolderManagement

# Database configuration
spring.datasource.url=jdbc:mysql://localhost:3366/card_holder_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA/Hibernate configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Fallback to H2 if MySQL fails
spring.datasource.hikari.initialization-fail-timeout=0
spring.jpa.defer-datasource-initialization=true

# Server configuration
server.port=6060

# Thymeleaf configuration
spring.thymeleaf.cache=false
spring.thymeleaf.enabled=true
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# Suppress static resource warnings
logging.level.org.springframework.web.servlet.resource=WARN
spring.web.resources.static-locations=classpath:/static/

# Enable SQL script execution
#spring.jpa.defer-datasource-initialization=true
#spring.sql.init.mode=always
#spring.sql.init.data-locations=classpath:data.sql